---
AWSTemplateFormatVersion: 2010-09-09
Description: |
  Template for a standard perm-space bucket with encryption, intelligent tiering, and versioning
  Note:  in work environment, object-level logging is already enabled for all S3 buckets in CloudTrail. Test if bucket name is available curl -sI https://<>.s3.amazonaws.com | grep bucket-region 


Parameters:
  BucketName:
    Type: String
    ConstraintDescription: Can only contain alphanumeric characters, spaces, dashes and underscores
    Description: Name for S3 Bucket. S3 bucket names are globally unique and map to DNS names, so its possible to use integer IDs to avoid leaking public info about projects

  LogBucketName:
   Type: String
   ConstraintDescription: Can only contain alphanumeric characters, spaces, dashes and underscores
   Description: Where access logs for the bucket will be delivered
   Default: my-bucket-logs

  DataClassificationTag:
    Description: Classification for the data stored in this stack
    Type: String
    Default: internal
    AllowedValues:
      - critical
      - restricted
      - internal
      - public

  EnvironmentTag:
      Description: In Which AWS Environment are you deploying?
      Type: String
      Default: non-prod
      AllowedValues:
        - non-prod
        - prod

  OwnerTag:
    Description: Individuals responsible for the resources
    AllowedPattern: "[-_a-zA-Z0-9]*"
    ConstraintDescription: Can only contain alphanumeric characters, spaces, dashes and underscores
    MinLength: "4"
    MaxLength: "64"
    Type: String

  ProjectTag:
    Description: Project title
    AllowedPattern: "[-_a-zA-Z0-9]*"
    ConstraintDescription: Can only contain alphanumeric characters, spaces, dashes and underscores
    MinLength: "4"
    MaxLength: "64"
    Type: String


  #RegulatedTag:
  #    Description: Should the resources deployed with this stack be tracked as regulated
  #    Type: String
  #    Default: "no"
  #    AllowedValues:
  #      - sox
  #      - gxp
  #      - "no"


Metadata:
    AWS::CloudFormation::Interface:
      ParameterGroups:
        -
          Label:
            default: "Tags"
          Parameters:
            - DataClassificationTag
            - EnvironmentTag
            - OwnerTag
            - ProjectTag

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: Private
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - AbortIncompleteMultipartUpload:
            DaysAfterInitiation:  7
          Status: Enabled
        # Old versions retained long term in case of questions about who overwrote or deleted data.
        # 395 days = 1 year + 1 month
        - NoncurrentVersionExpirationInDays: 395
          Status: Enabled
        - NoncurrentVersionTransition:
            StorageClass: GLACIER
            TransitionInDays: 30
          Status: Enabled
          # Transition - Move objects to a cheaper storage class
        - Transition:
            StorageClass: INTELLIGENT_TIERING
            TransitionInDays: 30
          Status: Enabled

      Tags:
          - Key: "bay:owner"
            Value: !Ref OwnerTag
          - Key: "bay:env"
            Value: !Ref EnvironmentTag
          - Key: "bay:project"
            Value: !Ref ProjectTag
          - Key: "bay:data-classification"
            Value: !Ref DataClassificationTag

Outputs:
  BucketName:
    Value: !Ref BucketName
    Description: Name of S3 bucket with lifecycle config
